### ISSUE TITLE
Omit Fields Instead of Returning String "None"

### ISSUE THREAD

**Issue by rawkode** [cfpland/api#10]
This existence of "None" contradicts the emptiness of the value and makes parsing the JSON through deserialisers rather tricky, as we'd need to provide special handling for "None" value.

Can these optional fields be omitted instead?

**Comment by karllhughes** [comment]
We could probably do that, but it would be a breaking change so it might require a new major version release.

Which fields are coming back as "None"? It's been a while since I tinkered with the API here.

**Comment by rawkode** [comment]
Maybe returning an empty string is less breaking, rather than omitting the field?

**Comment by rawkode** [comment]
I'm currently having to handle "None" for continent / region
